text/merklization.tex

Simplify trie definition for the in-memory trie

---

text/definitions.tex

$\mathsf{X}_E$ is mentioned here but not in the definitions section:
https://github.com/gavofyork/graypaper/blob/92a6d47bd0022524c923b0677c92a046eb805016/text/safrole.tex#L129-L130

Mention X_E in the definitions

---

text/judgements.tex
text/notation.tex
text/reporting_assurance.tex

Also, add an extra field for judgements.

Should be using posterior key sets for guarantors of last rotation

---

text/merklization.tex

Base case for trace

---

text/serialization.tex

replace curly with round brackets

fix(serialization): wrong notation

---

text/accounts.tex
text/accumulation.tex
text/ack.tex
text/auditing.tex
text/authorization.tex
text/bandersnatch.tex
text/definitions.tex
text/merklization.tex
text/overview.tex
text/pvm.tex
text/reporting_assurance.tex
text/safrole.tex
text/work_packages_and_reports.tex

Various minor fixes. Don't think there should be anything controversial here.

Minor fixes

---

text/notation.tex

Change merklization bit order for a more convinient key ordering

---

text/accumulation.tex

add missing argument `f` the dictionary of
privileged always-accumulate services 
into invocations of Delta_1

missing arg to Delta_1

---

text/accumulation.tex

the hash of the payload is defined as `l` in eq 122

fix subscript in Eq 175

---

text/accumulation.tex

updated Equations 165, 166 (Preimage Integration)

Refinement Context prerequisite is a set

---

text/header.tex
text/safrole.tex

Closes https://github.com/gavofyork/graypaper/issues/125

Include n_2 in epoch marker

---

text/pvm_invocations.tex

add missing G function in section B.10
on the inner call to info in accumulate's host function F

add call to G function for info call

---

text/merklization.tex

It probably should be v, not s

Fix leaf page function s -> v

---

text/definitions.tex
text/pvm_invocations.tex

PVM Host-calls: Host-call to inspect preimage request status

---

text/definitions.tex
text/pvm_invocations.tex

PVM Invocations: Yielding accumulation hash possible on OOG

---

text/notation.tex
text/pvm.tex

Closes #144 
https://hackmd.io/@koute/SJxTlrxN1g

PVM: Bit manipulation (Zbb-inspired) extensions

---

text/accumulation.tex
text/definitions.tex
text/pvm_invocations.tex

Accumulation & PVM Invocations: Buddy ejects service to allow perfect service deletion

---

text/work_packages_and_reports.tex

WP&WRs: Avoid referring to defunct function

---

text/pvm_invocations.tex
text/work_packages_and_reports.tex

`fetch` replaces `import`

---

text/overview.tex

Two minor typographic formatting corrections.

Typographic formatting corrections

---

text/pvm_invocations.tex

PVM Invocations: Clean up host-call formalisms

---

preamble.tex
text/accounts.tex
text/pvm_invocations.tex
text/work_packages_and_reports.tex

Closes https://github.com/gavofyork/graypaper/issues/257

Introduce metadata prefix into authorizer/service code blobs

---

preamble.tex
text/accumulation.tex
text/reporting_assurance.tex
text/serialization.tex
text/work_packages_and_reports.tex

Closes https://github.com/gavofyork/graypaper/issues/258

Accumulation: Accumulate items have additional information

---

text/definitions.tex
text/work_packages_and_reports.tex

Closes https://github.com/gavofyork/graypaper/issues/211

Misc: Update limits

---

text/reporting_assurance.tex

Chapter 11 was talking about work reports and mentions their work items when it should be work result.

Chapter 11: Correct work item to result since it's talking about work reports

---

text/pvm.tex

Register values are always non-negative naturals, just like #262

Registers are non-negative naturals

---

text/pvm.tex

PVM: Fix Host-call instruction counter value

---

text/definitions.tex
text/pvm_invocations.tex

Closes https://github.com/gavofyork/graypaper/issues/268

Fix the definition of sans-D

---

text/reporting_assurance.tex

this pr contains a minor grammatical hotfix & verbiage alignment
- `limit` feels like a better fit than `ratio` here based on the fields usage
- remove erroneous instance of the word:`of`
- update the sentence to be a bit more succinct
this change is opinionated, so open to changing/cancelling this pr if it's not worth landing

[nit] grammar & verbiage

---

preamble.tex
text/accumulation.tex
text/definitions.tex
text/pvm_invocations.tex
text/serialization.tex

Accumulation: Introduce gas limit into operand tuples

---

text/accumulation.tex
text/pvm_invocations.tex

Closes https://github.com/gavofyork/graypaper/issues/311
TODO:

Introduce `provide` host-call

---

text/pvm_invocations.tex

Fixes provide host function.
- registers
- `bold_d` (service dictionary)

PVM Invocations: `provide` registers and dictionary

---

text/merklization.tex

Perhaps a less confusing alternative to https://github.com/gavofyork/graypaper/pull/353

Reduce the size of state key(s) to 31 octets

---

text/pvm_invocations.tex

PVM Invocations: Maximum code size during Accumulate

---

text/definitions.tex
text/pvm_invocations.tex
text/work_packages_and_reports.tex

PVM Invocations: Introduce max code size for IsAuthorized

---

preamble.tex
text/erasure_coding.tex
text/reporting_assurance.tex
text/serialization.tex
text/work_packages_and_reports.tex

Closes https://github.com/gavofyork/graypaper/issues/287

WPs&WRs: Gracefully handle oversize reports

---

text/definitions.tex
text/pvm_invocations.tex

Closes https://github.com/gavofyork/graypaper/issues/349
Closes https://github.com/gavofyork/graypaper/issues/329

PVM Invocations: Introduce `entropy`/`config` host-calls

---

text/best_chain.tex
text/pvm_invocations.tex

Grandpa: Finalise posterior state root

---

text/pvm_invocations.tex

PVM Invocations: Refine `fetch` can get summary of work-item

---

text/definitions.tex
text/pvm_invocations.tex

PVM Invocations: Introduce `inspect_package` host-call

---

text/accounts.tex
text/accumulation.tex
text/merklization.tex
text/pvm_invocations.tex
text/reporting_assurance.tex

Closes #388 
This also cleans up several equations and introduces the ability for the manager service to imbue new services with gratis storage.

Accounts: Account metadata

---

preamble.tex
text/accumulation.tex
text/beefy.tex
text/definitions.tex
text/merklization.tex
text/overview.tex
text/recent_history.tex
text/reporting_assurance.tex

Recent Blocks: AccOuts in state, store historical roots only

---

text/definitions.tex
text/work_packages_and_reports.tex

WPs&WRs: Fix upper bundle size limit

---

text/work_packages_and_reports.tex

Fix Report Oversize Handling in Refine Invoc.

---

context.tex
preamble.tex
text/accounts.tex
text/accumulation.tex
text/auditing.tex
text/authorization.tex
text/beefy.tex
text/conclusion.tex
text/definitions.tex
text/erasure_coding.tex
text/header.tex
text/judgments.tex
text/merklization.tex
text/notation.tex
text/overview.tex
text/pvm.tex
text/pvm_invocations.tex
text/recent_history.tex
text/reporting_assurance.tex
text/safrole.tex
text/statistics.tex
text/work_packages_and_reports.tex

Closes https://github.com/gavofyork/graypaper/issues/266

Macro Marathon, Part IX

---

text/overview.tex

Could be wrong here, but it seems like we only need E_A and ρ† to get W.

W* depends on ρ† and not ρ'

---

text/guaranteeing.tex
text/pvm_invocations.tex
text/work_packages_and_reports.tex

PVM Invocations: Add core index to Refinement args

---

preamble.tex
text/accounts.tex
text/accumulation.tex
text/definitions.tex
text/merklization.tex
text/pvm_invocations.tex

Misc: Small service IDs

---

text/accumulation.tex
text/pvm_invocations.tex

Closes https://github.com/gavofyork/graypaper/issues/474

Accumulation: Owned Privileges

---

text/accumulation.tex

By reusing the preimage integration function defined earlier.

Simplify preimage integration section

---

text/pvm.tex
text/pvm_invocations.tex

Supersedes https://github.com/gavofyork/graypaper/pull/485

PVM: Fix up text and defs

---

preamble.tex
text/definitions.tex
text/work_packages_and_reports.tex

Closes https://github.com/gavofyork/graypaper/issues/458

WPs&WRs: Fix up the WP size limits
