- text/header.tex
- text/judgements.tex
- text/recent_history.tex
- text/reporting_assurance.tex
- text/safrole.tex
- Noted in the lecture that N sub V should use san-serif V. Replaced other such instances assuming the same.
- Noted in the lecture that `k_e` is incorrect, and should be `k_b` referencing the bandersnatch keys
- Number of cores should use san-serif `C`
- Removes a hanging apostrophe in "Jugements > Extrinsics"
- Removes `\seq{\H_B}_{2:3}` from the definition of J, the sequence of judgements introduced in the block’s extrinsic. (As noted in class)
> Fixes from Singapore PBA Lecture

- text/merklization.tex
0-size values should be embedded for simplicity. This is compatible with the rest of the spec.
> Zero sized values are embedded in the trie

- README.md
- preamble.tex
- text/authorization.tex
- text/definitions.tex
- text/header.tex
- text/judgements.tex
- text/recent_history.tex
- text/reporting_assurance.tex
- text/safrole.tex
- text/serialization.tex
- text/work_packages_and_reports.tex
> Various fixes for Elves security

- text/pvm.tex
The GP defines the `trap` instruction to be a halt, but this instruction was always meant to be used for *abnormal* termination (and in fact the compiler *will* use it when e.g. you do a `panic!` in Rust, or an assertion fails, etc.).
> Redefine `trap` to be a panic instead of a halt

- text/pvm.tex
This PR updates the instruction decoding equations for PVM.
These match with what I have currently implemented.
~~There's one more discrepancy that I have not addressed: in `A.5.8.` the upper bits of the byte are used as a destination register (this is inverse of what I have implemented) and in `A.5.11.` the destination register is in the lower bits of the byte (which matches what I have implemented). Ultimately it doesn't matter which one we pick, but it'd be nice to have it be consistent, so we should either adjust how GP defines `A.5.8.`, or we should adjust how GP defines `A.5.11.` and I'll change my implementation to match.~~ I've swapped the arguments.
> Update PVM instruction decoding equations

- text/pvm.tex
There is no need to floor on `mod` operation.
> fix(pvm): remove \floor in modulo operations

- text/definitions.tex
- text/pvm.tex
Since we've added support for the `C` extension the dynamic address alignment can now be 2.
> Change dynamic address alignment to 2

- text/overview.tex
as described in formula:
π'0[v]g ≡ a[v]g + (κ'v ∈ R)
Also removed dependency on tau', as tau' is already present in H, so it is redundant.
> Pi' Depends on kappa'

- text/recent_history.tex
- text/serialization.tex
- Fix serialization order in eq 283 (work report) to be coherent with eq 117:
- 117: (s, x, c, a, o, r)
- 283: WAS (a, c, o, x, s, r)
The serialization order of items in the other types is consistent with the definitions of those types, so this may be a leftover
- Fix naming for work items entry in eq 284 ($x_i -> x_w$) to be coherent with eq 174
- Adjust naming in eq 277 of dispute verdicts to be coherent with naming used in eq 97/98
I.e. Dispute extrinsic is now $E_D ≡ (v,c,f)$ and $(r,a,j) ∈ v$
- Encode verdict age as $E_4$
---
- **Not related to serialization**: Add hashing algorithm argument to MMR accumulate call
> Serialization adjustments

- text/accumulation.tex
- text/bandersnatch.tex
- text/pvm.tex
- text/pvm_invocations.tex
- text/reporting_assurance.tex
- Fix discrepency between Phi and Phi_1
- Bandersnatch: Use padding point for bad keys in ring
- PVM: Fix Skip function
- PVM: A.6: x' -> x 
- PVM: Typo Omega_X should be Omega_Q
- PVM host calls: Val key is 336 long
- Accumulation: Memos are 128 bytes
- Reporting/Assurance: a_v should be a_f
> Minor corrections

- text/reporting_assurance.tex
Fixes: https://github.com/gavofyork/graypaper/issues/73
> Reporting/Assurance: Fix text referencing old concept

- text/accumulation.tex
- text/erasure_coding.tex
- text/pvm.tex
- text/pvm_invocations.tex
- text/serialization.tex
> Misc Corrections

- text/accumulation.tex
ΨT has a natural `N_s` as second argument, not an account
> fix-179: δ′ calculation after 0.4.1

- text/accumulation.tex
Second argument is not necessary. Also, g is a sequence, so should really compare to [] not {}.
> Simplify definition of Q

- text/accumulation.tex
- text/definitions.tex
- text/recent_history.tex
- text/reporting_assurance.tex
- text/serialization.tex
Fixes #103 
- The WP/WR prerequisite is a set rather than an optional value.
- The size of the set of a WR's prerequisites plus the size of said WR's SR lookup dictionary must total no more than 8.
- All dependencies (defined as the set of prerequisites in union with the keys of the SR lookup dictionary) must have been recently reported at the time of reporting.
- A mapping of WPH->SR is no longer retained in Accumulated.
- A mapping of WPH->SR is maintained now in Recent Blocks ($\beta$).
- SR lookups are validated immediately upon reporting. It is up to the block producer to ensure that they are legit since a block is invalid if the SR lookups cannot be validated.
> Prerequisite is a set, ensure all dependencies are known/valid when reported

- text/overview.tex
- Removes `ψ'` from GP-0.4.3-eq:21 and adds `ψ'` to GP-0.4.3-eq:19. 
- Fixes: https://github.com/gavofyork/graypaper/issues/117
> Correction Dependencies STF gamma and kappa

- text/safrole.tex
For correctly verify the first block of a new epoch, we must first apply the new epoch entropy (i.e., n3←n2), as the first block ticket is generated using the same logic as all other tickets (i.e., utilizing n2 from the previous epoch).
> block seal utilizes posterior entropy

- text/pvm_invocations.tex
- remove extra `G()` in accumulate invocation mutator F
- fix a typo in G function in accumulate invocation
- fix extra `b` and related typo in `new` function
> small pvm invocation fixes

- text/pvm.tex
1. In GP-0.5.0-eq:A.11: Allow 8 input octets for the signed extension function as a consequence of the change to a 64bit architecture. Direct evidence of this requirement in instructions 141 & 142.
2. In GP-0.5.0-eq:A.20: add mod2^32 to instruction 72.
> Allow 8 octets input signed extension function (64bit)

- text/auditing.tex
Instead of their posterior validator set.
The prior validator set needs to be used by GRANDPA for validator set handover to work properly. Specifically, the first block in an epoch must be finalized by the previous validator set. This ensures that there is an unequivocal starting point for the next validator set, and there is no possibility of accidentally "unfinalizing" a block.
The validator set used for auditing should match the set used by GRANDPA, as validators use auditing results to determine how they vote in GRANDPA. Hence the change to use the prior validator set for auditing.
> Change blocks to be audited by their prior validator set

- text/pvm_invocations.tex
we currently have 
the otherwise branch doesn't make sense , as return value should be A (service account)
this PR aims to correct that
> fix: On-Transfer Invocation return value

- text/reporting_assurance.tex
We need to first update the recent block history (last block state root as per [GP 0.5.2 - 7.2](https://graypaper.fluffylabs.dev/#/5b732de/0fd5010fd501) to correctly compare state root ($y_s$) of last imported block with $x_s$  as per [GP 0.5.2 - 11.34](https://graypaper.fluffylabs.dev/#/5b732de/156701156701)
> Use beta_dagger for WR guarantees context check

- text/pvm_invocations.tex
Fix inconsistency in `designate` host function.
https://graypaper.fluffylabs.dev/#/5b732de/306401306401
Two instances of replacing `bold_i` with `bold_v`. Suggest to not use `bold_i` here, reasons: ambiguity and inconsistency.
> Inconsistency Designate Host Function

- text/merklization.tex
See https://github.com/w3f/jamtestvectors/pull/14#issuecomment-2549423040
> Fixed embedded merkle node size bit slice

- preamble.tex
- text/definitions.tex
- text/merklization.tex
- text/pvm_invocations.tex
- text/reporting_assurance.tex
- text/serialization.tex
- text/work_packages_and_reports.tex
- [Definitions: Update gas limits so that gas = nanoseconds](https://github.com/gavofyork/graypaper/pull/160/commits/83f7ad5601df239040c7caa4c0b52b590205f997)
- [WP&WRs: Badly reported exports count doesn't invalidate WP](https://github.com/gavofyork/graypaper/pull/160/commits/184515d80354f96f0410b48cea950ed7c9e4f03f)
- [ReportingAssurance: Active removal of expired reports](https://github.com/gavofyork/graypaper/pull/160/commits/3e99734afc3770b145539f20b1cfa2939bbecd80)
> Corrections on 0.5.2

- text/serialization.tex
B.14, On-Transfer Invocation calls for encoding of sequence of T deferred transfer
this PR adds the otherwise missing encoding specification
> Deferred Transfer encoding

- text/pvm.tex
- fix a few missed `Q()` -> `Z()` in Standard Program Initialization
> fix standard program init missed changes

- text/merklization.tex
add length discriminator to the encoding of the set of dependencies of ready to accumulate state item
https://graypaper.fluffylabs.dev/#/6e1c0cd/37f40137f401
> length discriminator encoding on ϑ dependencies

- text/pvm.tex
As reported here: https://github.com/w3f/jamtestvectors/pull/3#issuecomment-2626488823
> PVM: add missing sign extension to `div_u_32`

- text/pvm.tex
- Added unsigned conversion to `max`/`min` results so they can be assigned to the destination register
> PVM: Add unsigned conversion to max/min results

- text/header.tex
This PR sets `H_a` (GP-0.6.2-eq:5.9) with Bandersnatch key and not the entire key-set by adding attribute `b` as specified by GP-0.6.2-eq:6.9.
Supported by:
- GP text above equation 5.9 that states H_a only concerns the Bandersnatch key.
- The use of H_a in utility function Y.
> Set H_a with Bandersnatch key and not the entire key-set

- text/pvm_invocations.tex
- text/work_packages_and_reports.tex
The auth code hash is passed as the arg to Refine instead of the overall authorizer hash.
> PVM Invocation: `fetch`able auth details

- text/work_packages_and_reports.tex
not hash of code with param.
Closes #238
> WPs&WRs: AuthorizerHash is hash of codehash with param

- text/accumulation.tex
As per update #122 , the queue-editing function *E* takes a **set** of now-accumulated work package hashes as a parameter, and the WPH <> SR mapping validation is removed from the function. Updated the description to match the equation.
> Update description of accumulate queue-editing function

- text/intro.tex
"Size-synchrony antagonism" is used only once, but it must refer to the "size-coherency antagonism" discussed in the next chapter (and to "coherency" defined above).
Also added newline at end of file.
> Intro: Change "size-synchrony" to "size-coherency"

- text/pvm_invocations.tex
fix a small inconsistency in refine context type, it's `G` [here](https://graypaper.fluffylabs.dev/#/5f542d7/338202338402), but `Y` in equation B.3, B.4, I think they should be `G`
> fix refine context type

- text/overview.tex
β′ requires the commitment map which doesn't exist at it's current point in the dependency graph.
This PR corrects the order.
> Update stf dependency order for β′

- text/overview.tex
NOTE: supersedes https://github.com/gavofyork/graypaper/pull/241 (fixes mistake and resolves merge conflict).
Adds tau `τ` & tau_prime `τ'` as state transition input dependency in GP-0.6.2-eq:4.17 (1)
- GP-0.6.2-eq:12.24 (setting delta_doubledagger `δ‡`) (2)
- GP-0.6.2-eq:12.27 (setting theta_prime `ϑ'`) (3)
1. [GP-0.6.2-eq:4.17](https://graypaper.fluffylabs.dev/#/5f542d7/093a01093a01)
2. [GP-0.6.2-eq:12.24](https://graypaper.fluffylabs.dev/#/5f542d7/17db0317db03)
3. [GP-0.6.2-eq:12.27](https://graypaper.fluffylabs.dev/#/5f542d7/176304176304)
> Add tau & tau_prime as state transition input dependency (2nd try)

- text/serialization.tex
In the v0.6.3, 
But missing update $l$ to $y$ in serialization section
> missing update l to y in seL

- text/overview.tex
Added all references to synchronous entanglements based on the text context, instead of only some as before. Also sorted them in ascending order.
> Updated refs to synchronous entanglements

- text/accumulation.tex
In Accumulation parallelized accumulation function:
the service `a` should transition **q**
and the service `v` should transition **i**
quoting  from [9.4](https://graypaper.fluffylabs.dev/#/5f542d7/116f01116f01?v=0.6.3):
_χa and χv , are each the indices of services able to alter φ and ι from block to block._
> Accumulation: parallelized accumulation function: switch priviliged services indices

- biblio.bib
- text/bandersnatch.tex
**Specification Reference Update**  
- The latest specification introduces breaking changes, rendering it incompatible with the initial version (e.g. base point changes, ring-proof now works with TE points).  
- Test vectors in the document have been revised, and the example sources now align with the [published reference implementation](https://crates.io/crates/ark-ec-vrfs).  
**Bandersnatch VRF Section Update**  
- The  *verify* and *output* interface has been simplified by consolidating the separate `proof` and `output` parameters into a single proof parameter, which remains opaque from the GP perspective.  
- Instructions for interpreting this *proof* param are outlined in the Bandersnatch VRF spec.
- Polynomial commitment scheme is defined in Bandersnatch VRF spec
> Refine Bandersnatch-VRF section

- text/header.tex
- text/safrole.tex
This is useful for GRANDPA and calculating assurer sets for past epochs.
> Include ed25519 keys in the epoch marker

- text/merklization.tex
The C(13) in the statistic serialization (Appendix D. State Merklization) incorrectly used pi_C in the first position. This commit updates it to pi_V to ensure the correct variable is used in the formula. (v0.6.4)
> fix: use pi_V instead of pi_C in serialization

- text/reporting_assurance.tex
My initial change was to add explicit serialization before hashing the work report in equation 5.6 (#295). The intention was to make this consistent with how it was done in equation 11.26. But given the mention of section 3.8.1, it makes sense that this should also not explicitly serialize because it's not ambiguous. (also I should have noticed that everywhere else is just H(w) , it's just that 11.26 was the first example I came across :))
> Remove unnecessary serialization before hashing

- text/accumulation.tex
Void sequence `U ≡ ⟦ (NS, NG) ⟧` is missing in the outer accumulation function when `i = 0`
> Add missing void service/gas pair sequence in the outer accumulation function

- text/accounts.tex
This PR corrects a typo in the historical lookup function, updating `C_D` to `D` as mentioned earlier in the element channel.
> Accounts: use constant `D` in historical lookup function description

- text/pvm.tex
- text/pvm_invocations.tex
As clarified by @gavofyork in Element graypaper room, `\subseteq` should be used for memory accessibility check instead of `\subset`.
> PVM: Use `\subseteq` for memory accessibility check

- text/work_packages_and_reports.tex
In the work package gas limit constraints, work item refine gas limit should be `g`, not `r`.
> WPs&WRs: Fix typo in WP gas limit constraints

- text/reporting_assurance.tex
Reordered paragraphs in work-result section to place the `\mathbb{J}` description right after its equation for better flow. Previously, the order was (`\mathbb{J}` equation -> five activity fields description -> `\mathbb{J}` description).
> Reorder work-result paragraphs

- text/header.tex
I might be missing something here but the explicit serialization around the tuple seems redundant and removing it seems more in line with similar equations for the other extrinsics in the appendix.
> Remove unambigious serialization

- text/work_packages_and_reports.tex
The work item resultant datum d has a typo, should be  \mathbf{d} according to function C below
https://graypaper.fluffylabs.dev/#/68eaa1f/1a45011a4501?v=0.6.4
> fix: work item resultant datum d typo

- text/pvm_invocations.tex
in the accumulate invocation function, initializing an inner context when the accounts code isn't available as defined in [B.9](https://graypaper.fluffylabs.dev/#/68eaa1f/2eb3002eb300?v=0.6.4) is moot
this pr removes the `I(u, s)` function call and instead returns **u** directly
> [cleanup] skip moot context initialization

- text/work_packages_and_reports.tex
The previous wording seemed to imply that `\segsX` meant "all segments exported by all work-packages exporting a segment to be imported".
> Clarify commentary following data availability specification definition

- text/accumulation.tex
Fixed typos in the new preimage integration function:
1. Updated `τ'` into `[τ']` to represent timeslot sequence.
2. Use `()` for \hash - previously the hash function didn't render correctly:
> Fix typos in preimage integration function

- text/pvm.tex
[Program initialization function](https://graypaper.fluffylabs.dev/#/cc517d7/2b64022b6402?v=0.6.5) `Y` expects the program blob `p` to include the argument `a` (per Eq. A.37). 
We now invoke  
`$Y(p, a)`
instead of  
`Y(p)`  
**Changes**  
- In the definition of `\Psi_M`, updated both `Y(p) = …` matches to `Y(p,a) = …`.
- Y accepts **a** as a function argument
- Modified A.37 where we were earlier decoding **a** from **p**
> PVM Invocations: Fix up program init function

- text/accumulation.tex
Minor omission due to renaming of `p`-to-`i` in single-service accumulation function.
> Text change: equation 12.20: change p -> i

- text/overview.tex
- text/statistics.tex
This makes it on-par with how `C` (beefy commitments) are passed around in the STF overview.
It also seems like section 13 is no longer just validator statistics, but rather statistics about: 
1. (per epoch) validators
2. (per block) cores / services
I proposed my wording of this, but happy to remove/change that out if preferred.
> make it clearer that statistics relies on `I` and `X`

- text/intro.tex
- text/overview.tex
- text/pvm.tex
As per discussions on the graypaper chat and the change that was made in [jam-docs](https://github.com/JamBrains/jam-docs/pull/39).
> Terminology: rename instances of Polka Virtual Machine to Polkadot Virtual Machine

- text/accumulation.tex
- text/definitions.tex
- text/pvm_invocations.tex
- text/serialization.tex
Closes #250 
Closes #373
This removes `entropy` and `inspect_package` and enables `fetch` in all invocations, albeit with different fetch-indices enabled.
It allows `fetch` to be used in the OnTransfer context for fetching transfer records and in the Accumulation context for fetching items.
Invocation parameters for Accumulate and OnTransfer are altered to remove all unbounded elements and instead provide only item counts.
The order of fields in the Accumulation Operand Tuple is altered slightly to allow for efficient extraction of the result without concern to the auth trace.
> PVM Invocations: super-`fetch`; no unbounded invocation params

- text/pvm.tex
This PR introduces stricter validity requirements for instruction opcodes and jump targets. This only affects programs which contain "abnormal" PVM bytecode, and removes numerous corner cases which implementations (especially those implementing a recompiler) would have to otherwise handle.
- Every valid instruction must now have the bit for its opcode set to 1 in the bitmask to be considered valid.
- Jump targets (i.e. instruction offsets where basic blocks start) must also have the bit in the bitmask for their opcode set to 1, *and* their opcode must be defined by the GP to be considered valid.
- Unknown opcodes are now semantically treated as the `trap` instruction (including e.g. wrt to gas charging, which was previously left undefined), but due to the extra requirements wrt jump …
> PVM: stricter opcode/jump target validity requirements

- text/definitions.tex
- text/pvm_invocations.tex
This coalesces `void` and `zero` into a single host-call, `pages`.
`pages` takes a fourth tri-state argument denoting the access characteristics which the pages should have. To deallocate a page (previously `void` functionality), then a zero may be passed. To allocate read-write or clear existing read-write pages (previously `zero` functionality) then a 2 may be passed.
If a 1 is passed, then pages (whether presently accessible or not) are cleared and made read-only.
Closes #344
> PVM Invocations: Rearrange the inner PVM page admin

- text/pvm_invocations.tex
In #372, the Refine invocation function (`Ψ_R`) renamed the auth trace parameter from `\mathbf{o}` as `\mathbf{r}`, this PR ensures consistency in the related symbols:
1. In `Ψ_R`, `\mathbf{r}` was earlier used to denote the result variable from `\Psi_M`. I've updated this to `\mathbf{o}` to represent the "output" value to avoid conflict with updated authority trace argument `\mathbf{r}`
2. Updating text definition `authorizer trace o` to `authorizer trace r`
Making this change to be carefully limited to adjusting only the \Psi_M result notation while preserving the auth trace parameter as \mathbf{r} per PR #372. This avoids potential confusion with the \Omega_Y fetch function which has a separate \mathbf{o} parameter unrelated to auth trace.
Changed to:
Note: While \¬authtrace is defined …
> Fix: Authorizer-trace symbol in the Refine invocation

- text/pvm_invocations.tex
While implementing the fetch function we noticed that the work-package context `px` should be serialised:
Change:
> fix: encode px in fetch invocation

- text/definitions.tex
- text/pvm_invocations.tex
Removed S, since it is not used (also from definitions)
Removed Wg (segment size), since it can be calculated as Wp*We
Added K (maximum number of tickets) and N (number of tickets per validator) for consistency. These may be resonably different between e.g. full and tiny config. It would make everyone's life easier if the same encoded struct can be used on-chain and off-chain to keep track of all the protocol parameters that may differ.
> PVM Invocations: Tweak chain params

- text/definitions.tex
Bandersnatch signatures are 96 octets, as described in:
https://github.com/gavofyork/graypaper/blob/69d3f5fd17dbcde4b39fab8f7f5588dc14a7a9bc/text/notation.tex#L165
https://github.com/gavofyork/graypaper/blob/69d3f5fd17dbcde4b39fab8f7f5588dc14a7a9bc/text/bandersnatch.tex#L8
> Definitions: Fix typo in Bandersnatch signature definition

- text/safrole.tex
0.7.0 shows this 
but it should instead use `posterior gamma S`
> Nit: typo fix in Sealing Entropy Accumulation

- text/pvm_invocations.tex
In `on_transfer`, deferred transfer amounts were added to transfer destination accounts' balance prior to invoking `Ψ_M`.
After merging `on_transfer` invocation into `accumulate`, the same process should be handled in the `accumulate` invocation.
(before)
(after)
> PVM Invocations: Add deferred transfers amount to accumulating account balance

- text/pvm_invocations.tex
Accumulate input variable was updated from **o** to **i** in #465, but missed updating the `FETCH` argument.
> PVM Invocation: Typo in `FETCH` accumulate input arg

- text/serialization.tex
In general, the Sigma sum notation (∑) uses inclusive start/end ranges. Other equations in GP follow this rule, e.g. [PVM instruction 102 & 103](https://graypaper.fluffylabs.dev/#/1c979cb/282102282102?v=0.7.1) and [Eq (H.9)](https://graypaper.fluffylabs.dev/#/1c979cb/3f71023f7102?v=0.7.1).
Updated bit sequence encoding function to follow this convention as well, ensuring it properly extracts 8 bits at once.
> Serialization: Correct bit sequence encoding range

- text/accumulation.tex
add the missing ordering for last accumulation output
the last accumulation output type is sequence in 
and outer accumulate returns B which is a set
-------
Changes
- before:
- after:
> Order lastaccout before assign to new state
